### ISSUE TITLE
How to authenticate?

### ISSUE THREAD

**Issue by ebuildy** [open-io/oio-api-java#50]
I didnt see any thing about login / password, how can I authenticate?

(swift client options: ``--os-tenant-name --os-username --os-password``)

Thanks you.

**Comment by jkasarherou** [comment]
Hi!
When using the native API no authentication mechanism is used, so no login/password is necessary.
If you use the Openstack Swift API or S3 access, you need to authenticate.

**Comment by ebuildy** [comment]
yes, this is what we are using, is it possible with your java client?

Thanks you,

**Comment by jkasarherou** [comment]
No this is the native API only. If you use S3 you can use any third-party java API compatible with S3.

**Comment by ebuildy** [comment]
ok thanks you very much.
